// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDFq98r2Kv9aRB1pavHImJucOUpyirjFc',
    appId: '1:206485582485:web:c517155281ed5c60ed219c',
    messagingSenderId: '206485582485',
    projectId: 'h4h-client',
    authDomain: 'h4h-client.firebaseapp.com',
    storageBucket: 'h4h-client.firebasestorage.app',
    measurementId: 'G-VYRFQ3MW8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3_ZjKrJEqklEt9gfyvYl4Uu3hnO4M644',
    appId: '1:206485582485:android:9e54a23b293ed852ed219c',
    messagingSenderId: '206485582485',
    projectId: 'h4h-client',
    storageBucket: 'h4h-client.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw5IxM7BFGm4UdxH0mZBmrao-Ll0J5dzw',
    appId: '1:206485582485:ios:6e0a2669ffa538c6ed219c',
    messagingSenderId: '206485582485',
    projectId: 'h4h-client',
    storageBucket: 'h4h-client.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw5IxM7BFGm4UdxH0mZBmrao-Ll0J5dzw',
    appId: '1:206485582485:ios:6e0a2669ffa538c6ed219c',
    messagingSenderId: '206485582485',
    projectId: 'h4h-client',
    storageBucket: 'h4h-client.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDFq98r2Kv9aRB1pavHImJucOUpyirjFc',
    appId: '1:206485582485:web:deccbfaadb52099aed219c',
    messagingSenderId: '206485582485',
    projectId: 'h4h-client',
    authDomain: 'h4h-client.firebaseapp.com',
    storageBucket: 'h4h-client.firebasestorage.app',
    measurementId: 'G-VSXTBEK2HX',
  );
}
