// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_eOLD8zM-CAPquhPgdf_3e1nLScuW0jQ',
    appId: '1:745638645574:web:64f6a98248776ad0b9df47',
    messagingSenderId: '745638645574',
    projectId: 'test-e1dc5',
    authDomain: 'test-e1dc5.firebaseapp.com',
    storageBucket: 'test-e1dc5.firebasestorage.app',
    measurementId: 'G-N5MLBV47ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVoY7dGTdG-8u9pZgCzIG7aI9xZznHhqk',
    appId: '1:745638645574:android:9fda9548867d3252b9df47',
    messagingSenderId: '745638645574',
    projectId: 'test-e1dc5',
    storageBucket: 'test-e1dc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5AjSf_6XXv12iGJ5GaKGM3AovJ4D3R4o',
    appId: '1:745638645574:ios:a1cc840cc25b143fb9df47',
    messagingSenderId: '745638645574',
    projectId: 'test-e1dc5',
    storageBucket: 'test-e1dc5.firebasestorage.app',
    iosBundleId: 'com.example.specjalistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5AjSf_6XXv12iGJ5GaKGM3AovJ4D3R4o',
    appId: '1:745638645574:ios:a1cc840cc25b143fb9df47',
    messagingSenderId: '745638645574',
    projectId: 'test-e1dc5',
    storageBucket: 'test-e1dc5.firebasestorage.app',
    iosBundleId: 'com.example.specjalistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_eOLD8zM-CAPquhPgdf_3e1nLScuW0jQ',
    appId: '1:745638645574:web:c03e03b0a0e776f2b9df47',
    messagingSenderId: '745638645574',
    projectId: 'test-e1dc5',
    authDomain: 'test-e1dc5.firebaseapp.com',
    storageBucket: 'test-e1dc5.firebasestorage.app',
    measurementId: 'G-LRLFWS4HLE',
  );
}