name: specjalist_app
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  intl: ^0.19.0
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.0
  flutter_local_notifications: ^19.0.0
  image_picker: ^0.8.7+4
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/kot.jpg
    - lib/images/aaa.png
    - lib/images/ikona1.png
    - lib/images/ikona2.png
    - lib/images/ikona3.png
    - lib/images/ikona4.png
    - lib/images/ikona5.png
